import type { Locale } from '../i18n'

const en = {
  title: 'How it works',
  intro:
    'The platform has been designed as a modular pipeline composed of independent stages.',
  stages: [
    {
      title: '1. Dealer Discovery & Crawling',
      body: 'The system starts from an Excel database containing dealer information.\n\nUsing Playwright, it automatically explores each website, extracting:',
      bullets: [
        'Website pages',
        'Product catalogs',
        'Contact pages',
        'Team information',
        'PDF documents',
        'Email addresses',
        'Phone numbers',
        'Technical metadata',
      ],
      footer:
        'All collected information is stored as structured JSON, allowing future analysis without crawling the website again.',
    },
    {
      title: '2. AI Commercial Analysis',
      body: 'Once the crawling phase is complete, the platform supports two different workflows.',
      modes: [
        {
          title: 'Manual mode',
          body: 'The application automatically generates an optimized prompt containing all the collected information, ready to be copied into ChatGPT, Gemini or Claude.\n\nThe AI returns a structured JSON with the commercial profile of the dealer.',
        },
        {
          title: 'Automatic mode',
          body: 'Using the Gemini API, the platform sends the extracted information directly to an LLM, eliminating manual interaction and producing the final commercial analysis automatically.',
        },
      ],
    },
    {
      title: '3. Commercial Qualification',
      body: 'The AI analyzes each dealer and extracts key commercial information such as:',
      bullets: [
        'Business segment',
        'Geographic coverage',
        'Equipment portfolio',
        'Technical service capabilities',
        'Kitchen design services',
        'Showrooms',
        'Existing customer references',
        'Competitor detection',
        'Inside Sales identification',
        'Sales contacts',
        'Commercial suitability score',
        'Executive commercial summary',
      ],
      footer:
        'Every field includes traceability indicating the source page from which the information was extracted.',
    },
    {
      title: '4. Report Generation',
      body: 'The final structured data is exported back into Excel, creating a standardized commercial database that allows business teams to compare and prioritize hundreds of distributors consistently.',
    },
  ],
  architectureTitle: 'Architecture',
  architecture: `Dealer Database (Excel)
          │
          ▼
    Web Crawling
          │
          ▼
 Structured JSON Cache
          │
    ┌─────┴─────┐
    │           │
    Automatic AI
    (Gemini API)
    │           │
    └─────┬─────┘
          ▼
 Commercial Intelligence
          │
          ▼
 Structured JSON
          │
          ▼
 Updated Excel Report`,
  technologiesTitle: 'Technologies',
  technologies: [
    'Python',
    'Playwright',
    'Gemini API',
    'Large Language Models (LLMs)',
    'JSON Processing',
    'Excel Automation',
    'Prompt Engineering',
    'Web Crawling',
    'PDF Parsing',
  ],
  featuresTitle: 'Key Features',
  features: [
    'Automated website crawling',
    'PDF content extraction',
    'Intelligent prompt generation',
    'Manual and fully automated AI workflows',
    'Structured commercial profiling',
    'Competitor identification',
    'Inside Sales detection',
    'Sales contact extraction',
    'Executive summaries generated by AI',
    'Excel integration',
    'Modular pipeline architecture',
  ],
} as const

const es = {
  title: 'Cómo funciona',
  intro:
    'La plataforma se ha diseñado como un pipeline modular compuesto por etapas independientes.',
  stages: [
    {
      title: '1. Descubrimiento y crawling de dealers',
      body: 'El sistema parte de una base de datos Excel con información de dealers.\n\nCon Playwright, explora automáticamente cada sitio web y extrae:',
      bullets: [
        'Páginas del sitio web',
        'Catálogos de productos',
        'Páginas de contacto',
        'Información del equipo',
        'Documentos PDF',
        'Direcciones de email',
        'Números de teléfono',
        'Metadatos técnicos',
      ],
      footer:
        'Toda la información recopilada se almacena como JSON estructurado, lo que permite analizarla más adelante sin volver a rastrear el sitio web.',
    },
    {
      title: '2. Análisis comercial con IA',
      body: 'Una vez completada la fase de crawling, la plataforma admite dos flujos de trabajo distintos.',
      modes: [
        {
          title: 'Modo manual',
          body: 'La aplicación genera automáticamente un prompt optimizado con toda la información recopilada, listo para copiarse en ChatGPT, Gemini o Claude.\n\nLa IA devuelve un JSON estructurado con el perfil comercial del dealer.',
        },
        {
          title: 'Modo automático',
          body: 'Mediante la API de Gemini, la plataforma envía la información extraída directamente a un LLM, eliminando la interacción manual y produciendo el análisis comercial final de forma automática.',
        },
      ],
    },
    {
      title: '3. Cualificación comercial',
      body: 'La IA analiza cada dealer y extrae información comercial clave como:',
      bullets: [
        'Segmento de negocio',
        'Cobertura geográfica',
        'Portfolio de equipos',
        'Capacidades de servicio técnico',
        'Servicios de diseño de cocina',
        'Showrooms',
        'Referencias de clientes existentes',
        'Detección de competidores',
        'Identificación de Inside Sales',
        'Contactos comerciales',
        'Puntuación de idoneidad comercial',
        'Resumen comercial ejecutivo',
      ],
      footer:
        'Cada campo incluye trazabilidad que indica la página de origen de la que se extrajo la información.',
    },
    {
      title: '4. Generación de informes',
      body: 'Los datos estructurados finales se exportan de nuevo a Excel, creando una base de datos comercial estandarizada que permite a los equipos de negocio comparar y priorizar cientos de distribuidores de forma consistente.',
    },
  ],
  architectureTitle: 'Arquitectura',
  architecture: `Base de datos de dealers (Excel)
          │
          ▼
    Web Crawling
          │
          ▼
 Caché JSON estructurado
          │
    ┌─────┴─────┐
    │           │
    IA automática
    (API Gemini)
    │           │
    └─────┬─────┘
          ▼
 Inteligencia comercial
          │
          ▼
 JSON estructurado
          │
          ▼
 Informe Excel actualizado`,
  technologiesTitle: 'Tecnologías',
  technologies: [
    'Python',
    'Playwright',
    'API Gemini',
    'Large Language Models (LLMs)',
    'Procesamiento JSON',
    'Automatización Excel',
    'Prompt Engineering',
    'Web Crawling',
    'Análisis de PDF',
  ],
  featuresTitle: 'Funcionalidades clave',
  features: [
    'Crawling automatizado de sitios web',
    'Extracción de contenido PDF',
    'Generación inteligente de prompts',
    'Flujos de IA manuales y totalmente automatizados',
    'Perfilado comercial estructurado',
    'Identificación de competidores',
    'Detección de Inside Sales',
    'Extracción de contactos comerciales',
    'Resúmenes ejecutivos generados por IA',
    'Integración con Excel',
    'Arquitectura de pipeline modular',
  ],
} as const

const fr = {
  title: 'Comment ça marche',
  intro:
    'La plateforme a été conçue comme un pipeline modulaire composé d’étapes indépendantes.',
  stages: [
    {
      title: '1. Découverte et crawling des dealers',
      body: 'Le système part d’une base de données Excel contenant les informations des dealers.\n\nAvec Playwright, il explore automatiquement chaque site web et extrait :',
      bullets: [
        'Pages du site web',
        'Catalogues de produits',
        'Pages de contact',
        'Informations sur l’équipe',
        'Documents PDF',
        'Adresses e-mail',
        'Numéros de téléphone',
        'Métadonnées techniques',
      ],
      footer:
        'Toutes les informations collectées sont stockées en JSON structuré, ce qui permet de les analyser plus tard sans crawler à nouveau le site.',
    },
    {
      title: '2. Analyse commerciale par IA',
      body: 'Une fois la phase de crawling terminée, la plateforme prend en charge deux workflows distincts.',
      modes: [
        {
          title: 'Mode manuel',
          body: 'L’application génère automatiquement un prompt optimisé contenant toutes les informations collectées, prêt à être copié dans ChatGPT, Gemini ou Claude.\n\nL’IA renvoie un JSON structuré avec le profil commercial du dealer.',
        },
        {
          title: 'Mode automatique',
          body: 'Via l’API Gemini, la plateforme envoie les informations extraites directement à un LLM, éliminant l’interaction manuelle et produisant l’analyse commerciale finale automatiquement.',
        },
      ],
    },
    {
      title: '3. Qualification commerciale',
      body: 'L’IA analyse chaque dealer et extrait des informations commerciales clés telles que :',
      bullets: [
        'Segment d’activité',
        'Couverture géographique',
        'Portefeuille d’équipements',
        'Capacités de service technique',
        'Services de conception de cuisine',
        'Showrooms',
        'Références clients existantes',
        'Détection de concurrents',
        'Identification d’Inside Sales',
        'Contacts commerciaux',
        'Score d’adéquation commerciale',
        'Résumé commercial exécutif',
      ],
      footer:
        'Chaque champ inclut une traçabilité indiquant la page source à partir de laquelle l’information a été extraite.',
    },
    {
      title: '4. Génération de rapports',
      body: 'Les données structurées finales sont exportées vers Excel, créant une base commerciale standardisée qui permet aux équipes business de comparer et prioriser des centaines de distributeurs de façon cohérente.',
    },
  ],
  architectureTitle: 'Architecture',
  architecture: `Base dealers (Excel)
          │
          ▼
    Web Crawling
          │
          ▼
 Cache JSON structuré
          │
    ┌─────┴─────┐
    │           │
    IA automatique
    (API Gemini)
    │           │
    └─────┬─────┘
          ▼
 Intelligence commerciale
          │
          ▼
 JSON structuré
          │
          ▼
 Rapport Excel mis à jour`,
  technologiesTitle: 'Technologies',
  technologies: [
    'Python',
    'Playwright',
    'API Gemini',
    'Large Language Models (LLMs)',
    'Traitement JSON',
    'Automatisation Excel',
    'Prompt Engineering',
    'Web Crawling',
    'Analyse PDF',
  ],
  featuresTitle: 'Fonctionnalités clés',
  features: [
    'Crawling automatisé de sites web',
    'Extraction de contenu PDF',
    'Génération intelligente de prompts',
    'Workflows IA manuels et entièrement automatisés',
    'Profilage commercial structuré',
    'Identification des concurrents',
    'Détection d’Inside Sales',
    'Extraction de contacts commerciaux',
    'Résumés exécutifs générés par IA',
    'Intégration Excel',
    'Architecture de pipeline modulaire',
  ],
} as const

export const zumexHowItWorksByLocale = { en, es, fr } as const

export function getZumexHowItWorks(locale: Locale) {
  return zumexHowItWorksByLocale[locale]
}
